tap "goreleaser/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
#tap "homebrew/cask-versions"
tap "homebrew/core"
tap "osgeo/osgeo4mac"

brew "asciinema"
brew "bats-core"
brew "create-dmg"
brew "envchain"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "gnupg"
brew "go"
brew "go-bindata"
brew "goenv"
brew "gomplate"
brew "hub"
brew "imagemagick"
brew "jq"
brew "pkg-config"
brew "ripgrep"
brew "telnet"
brew "the_silver_searcher"
brew "tree"
brew "vault"
brew "watch"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "goreleaser/tap/goreleaser"
brew "zsh"

cask "amazon-music"
cask "encryptme"
cask "firefox"
cask "google-chrome"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "ngrok"
cask "monodraw"
cask "signal"
cask "slack"
cask "tableplus"
cask "visual-studio"
cask "vlc"
cask "zoomus"

mas "Pixelmator", id: 407963104
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353